# Generated by Django 2.2.7 on 2019-12-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('artist', '0001_initial'),
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_des', models.CharField(default='This is a popular Song!', max_length=250)),
                ('song_length', models.CharField(max_length=10)),
                ('song_file', models.FileField(upload_to='songs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.Genre')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood.Mood')),
            ],
        ),
    ]
